services:
  api:
    image: my-nest-api:latest
    build:
      context: ../..
      dockerfile: docker/api/Dockerfile
    container_name: my-nest-api-standalone
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:5432/my_nest_api
